### ISSUE TITLE
Week 7: To-Do

### ISSUE THREAD

**Issue by kobelschool** [marlinfiggins/spelhouse-drp-2023#10]
- [x] Add agent tracking
- [ ] Generate transmission tree
- [ ] Think about mathematics behind branching process, specifically extinction probability

Meeting Summary: Discussed some important changes needed for the branching process and clarified some misconceptions about immunity. Plotted data, and verified implementation of negative binomial distribution. Generated thoughts on the takeaways I valued most from the project, which will act as anchor points for the presentation.
