### ISSUE TITLE
Week 6: To-Do

### ISSUE THREAD

**Issue by kobelschool** [marlinfiggins/spelhouse-drp-2023#9]
During our meeting we discussed next steps for the project, specifically what to focus on during the coming weeks as the presentation approaches. First step is to flesh out the Galton Watson branching process implementation:
- [x] Negative Binomial Distribution Implementation (SciPyStats)
- [x] Freeze distributions (size of previous generation)
- [x] Batch simulations, running multiple realizations simultaneously
Extensions of the GW branching process could be
- Simulating finite population and/or some form of immunity
- Simulating infectious period
- Changing offspring distributions
Think about producing estimates for the following:
- Extinction probability
- Time to extinction
- Exponential Growth Rate

**Comment by kobelschool** [comment]
Ok, I am likely missing the point here, but how does one implement the batch process in a way that is actually more computationally efficient? Is the goal to do each generation for every realization concurrently? (That actually sounds really dope as I type it out) If so, how is that better than simply doing each realization one at a time and saving the results in an array, or vector. Like isn't it the same amount of actions being performed, unless the code is made in a vectorized format to reduce computations?

**Comment by marlinfiggins** [comment]
There's no real way to do concurrently I believe. What I'm referring to is having multiple simulation results saved in the same numpy array of shape (N_time_steps, N_realizations). This can be achieved in the way you describe: "doing each realization one at a time and saving results".

**Comment by kobelschool** [comment]
Ok, thanks for the clarification

**Comment by kobelschool** [comment]
I was able to do all of the checkmark items and make a simulation on a finite population with immunity after a provided number of time steps (could be easily converted to model infectious period as well). I had intended to work on the project for another hour or so, any advice on the next steps or should I just wait for tmrw's meeting? I know we had discussed that there was some degree of nuance to calculating the values listed, a quick refresh on what those nuances were would be appreciated.
